### PR TITLE
Test-Thumbprint: Check for FIPS

### PR DESCRIPTION
**Pull request by mcmcghee**
**Pull Request (PR) description**
Modification to Test-Thumbprint to check if FIPS is enabled. If enabled, only select FIPS compliant algorithms. 

**This Pull Request (PR) fixes the following issues:**
#107 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/108)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thank you very much for submitting this! Great stuff!

Is it possible to add a unit test so that we cover both FIPS and non-FIPS modes (just to ensure errors aren't thrown etc):
https://github.com/PowerShell/xCertificate/blob/dev/Tests/Unit/CertificateDsc.Common.Tests.ps1#L155

You could just Mock the `Get-ItemProperty` and have it return the Enabled = 0 or Enabled =1 for each test and make sure no errors are thrown.

Just one minor issue noted with handling it if the registry key is missing or inaccessible (for some strange reason - I've encountered problems like this before).

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xCertificate/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 117 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/108#-KyZ6JmotQIaXP-qhxnx:-KyZ6JmpIqszHqYZcb4Y:bfmdrdl) ([raw file](https://github.com/powershell/xcertificate/blob/c091381bf23ee9b904c04f5be4add41925b87db8/Modules/xCertificate/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L117)):*
> ```PowerShell
>     {
>         # Get FIPS registry key
>         $fips = (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy' | Select-Object -ExpandProperty 'Enabled')
> ```

If the `HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy` registry key does not exist then an exception will be thrown. Suggest adding `-ErrorAction SilentlyContinue` or a check for this.

So you could do something like:
```powershell
$fips =  [System.Int32] (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy' | Select-Object -ExpandProperty 'Enabled')
```

That way, even if the key does not exist, `$fips` will still end up as a `0`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/108#-:-KyZ8Bwn5hEGfboVAn3b:bnsa1ut)*

**Comment by PlagueHO** [comment]
Hi @mcmcghee - can you resolve the conflicts on this one?

**Comment by mcmcghee** [comment]
Sorry, I've been slammed.  I'm just getting into Pester and having a hard time determining the best way to implement the test. Assistance would be appreciated!

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xCertificate/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 117 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/108#-KyZ6JmotQIaXP-qhxnx:-L04wfiTQG4EcOOZuyrY:bt2vr1b) ([raw file](https://github.com/powershell/xcertificate/blob/c091381bf23ee9b904c04f5be4add41925b87db8/Modules/xCertificate/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L117)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If the `HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy` registry key does not exist then an exception will be thrown. Suggest adding `-ErrorAction SilentlyContinue` or a check for this.

So you could do something like:
```powershell
$fips =  [System.Int32] (Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy' | Select-Object -ExpandProperty 'Enabled')
```

That way, even if the key does not exist, `$fips` will still end up as a `0`.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/108#-:-L04wpnag_xwiRO0pg8J:b-32kr3n)*

**Comment by PlagueHO** [comment]
Thanks for your work on this @mcmcghee ! I can submit a PR to your branch with the tests you need - but it won't be till the weekend.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/108#-:-L08gZAT_yw2hIoTzwlH:bn8maax)*

**Comment by PlagueHO** [comment]
Sorry @mcmcghee - I haven't had any time to get the PR submitted to you (been a bit snowed under at work). I'll see what I can do this weekend.

**Comment by johlju** [comment]
@mcmcghee Sorry I saw that @PlagueHO had offered to help with the tests on this one. @PlagueHO is that on your (very) long to-do list? 🙂

**Comment by johlju** [comment]
@PlagueHO Great, would be good to get this one to the finish line. 🙂

**Comment by PlagueHO** [comment]
Hi @mcmcghee - sorry this took 6 months to get to!

Anyway, since you begun this PR we've actually renamed this entire repo to CertificateDsc and the resource name is now CertReq (not xCertReq). So your PR has a few merge conflicts to fix up. I also refactored the existing tests for this function because they didn't meet the current standards.

But, I have created the tests for this and also tweaked your code a little bit to optimize it a little (hope that is OK). You can copy the changes over here:

1. \Tests\Unit\CertificateDsc.Common.Tests.ps1:
a. Replace the `$validThumbprint = ...` block with: https://github.com/PlagueHO/CertificateDsc/blob/27ae9d726e674d4e2935cb528589af6088a70cb1/Tests/Unit/CertificateDsc.Common.Tests.ps1#L24-L46
b. Replace the `Describe "$DSCResourceName\Test-Thumbprint" {` block with: https://github.com/PlagueHO/CertificateDsc/blob/27ae9d726e674d4e2935cb528589af6088a70cb1/Tests/Unit/CertificateDsc.Common.Tests.ps1#L169-L263

2. Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1:
Replace `Begin` block in Test-Thumbprint function with: https://github.com/PlagueHO/CertificateDsc/blob/27ae9d726e674d4e2935cb528589af6088a70cb1/Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L115-L153

Let me know if you this doesn't make sense and I'll try and be more timely with my response! :grin:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/108#-:-LBmKmSt5fJ92pGyQvjY:bdnxb7x)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[CHANGELOG.md, line 15 at r3](https://reviewable.io/reviews/powershell/certificatedsc/108#-LBmMpsf0CUAkP5BukiJ:-LBmMpsf0CUAkP5BukiK:b-nmqe04) ([raw file](https://github.com/powershell/certificatedsc/blob/48036578e69e44571df1278c2aacfa3cfff5a427/CHANGELOG.md#L15)):*
> ```Markdown
>   module so is missing `Import-PfxCertificate` and `Import-Certificate`
>   cmdlets - fixes [Issue #46](https://github.com/PowerShell/xCertificate/issues/46).
> - Added detection for FIPS mode in Test-Thumbprint - see [Issue #107](https://github.com/PowerShell/xCertificate/issues/107).
> ```

The path of this issue should be ```https://github.com/PowerShell/CertificateDsc/issues/107```

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/108)*

**Comment by mcmcghee** [comment]
Thanks for the assistance! Being able to see how you implemented that test helps me a lot and makes sense now. 

Hopefully I committed these changes properly. Let me know if there's something I missed/need to do.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 15 at r3](https://reviewable.io/reviews/powershell/certificatedsc/108#-LBmMpsf0CUAkP5BukiJ:-LBvkeNJCMPNgCrJMDog:b-896fix) ([raw file](https://github.com/powershell/certificatedsc/blob/48036578e69e44571df1278c2aacfa3cfff5a427/CHANGELOG.md#L15)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

The path of this issue should be ```https://github.com/PowerShell/CertificateDsc/issues/107```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/108#-:-LBvkZbp3RwPbHRMrS3x:bsc5xua)*

**Comment by PlagueHO** [comment]
Nice! Great job @mcmcghee - thank you very much!

:lgtm:

---

Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/108#-:-LByVnXv4rPVJkjbE0AK:bvyiwcq)*

**Pull request merged**
