### PR TITLE
Update MSFT_PfxImport.psm1 - Fixes #129

### LINKED ISSUE #129: xPfxImport does not import after sysprep
**Details of the scenario you tried and the problem that is occurring:**

After syspreping a server, the certificate is left in the cert store but the private key is removed during the sysprep process. xPfxImport only checks to ensure the thumbprint is present. It does not check to see if the certificate has a private key so it never imports the pfx file and the certificate. 

**The DSC configuration that is using the resource (as detailed as possible):**

xPfxImport Wildcard
        {
            Thumbprint = $wildcardthumbprint
            Path       = $certificatepath
            Location   = 'LocalMachine'
            Store      = 'My'
            Exportable = $true
            Credential = $Credential1
            Ensure     = 'Present'
            DependsOn  = "[xDSCDomainjoin]JoinDomain"
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**

DSC running in Azure
OS version: 2012R2

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

xCertificate 3.2.0.0

### PR DESCRIPTION
**Pull request by mattbowes**
Add a check to see if the private key file is on the file system. After a sysprep .hasPrivateKey returns true even though the private key file on the file system is missing. This checks that the private key is there and that the file on the filesystem exists

**Pull Request (PR) description**
Checks the file system to see if the private key file exists. After a sysprep .hasPrivateKey returns true enough though the file is missing

**This Pull Request (PR) fixes the following issues:**
Fixes #129

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/134)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @mattbowes - great stuff! Can you add an entry to the CHANGELOG.MD describing the change and also linking to the issue in github? See previous changes for examples.

**Comment by mattbowes** [comment]
@PlagueHO, CHANGELOG.MD  updated, thank you for the help

**Comment by PlagueHO** [comment]
Just noticed the integration tests are failing. This may mean that the change is mis detecting that the private key doesnt exist in cases where it does exist. We'll need to have a look at this I think.

**Comment by PlagueHO** [comment]
See https://ci.appveyor.com/project/PowerShell/certificatedsc/build/2.3.15.0#L655

**Comment by mattbowes** [comment]
Dang, I thought this would fix it

**Comment by PlagueHO** [comment]
@mattbowes - I'll make a clone of one of my servers, create a cert and sysprep it and see if I can identify a way of checking if the private key exists. It may be something as primitive as just trying to use the private key and see if an error occurs.

**Comment by PlagueHO** [comment]
Sorry @mattbowes - I haven't got around to this one yet (it slipped my mind). I'll see if I can get this done tomorrow.

**Comment by mattbowes** [comment]
@PlagueHO No worries. I am also trying to find some free time at work to deploy a image and see what happens

**Comment by mattbowes** [comment]
Hi, I'd like to still help with this. I'm not sure what needs to be done though

**Comment by johlju** [comment]
@mattbowes Can you please make sure that the changes in PR #135 is instead added to this PR? Also this PR needs to be rebased due to recent merges in the dev-branch.

There are merge conflicts since your PR was not based on the latest changes. Could you please rebase against branch dev using `git rebase` (not by using `git pull` or `git merge`, to keep the commit history). If you don't know how to rebase your local dev and working branch, please look at how to [Resolve merge conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts).
Let me know if you need any assistance.

**Comment by PlagueHO** [comment]
Sorry, I thought I responded in here. I tried a whole bunch of things and just can't find a way where I can effectively detect if the private key exists after the image has been syspreped. I'm wondering if the best way is just to ensure the certificate doesn't exist on the machine before syspreping?

**Comment by mattbowes** [comment]
@PlagueHOIs Could there be a force option to force it to import the cert and privatekey even if it thinks it already exists

**Comment by PlagueHO** [comment]
@mattbowes - it is possible, but what would happen is that the certificate would be "set" everytime the DSC was applied - no matter what - even if the certificate is installed with Private Key. This sort of behavior is generally discouraged from DSC resources as it results in constant churn. E.g. the LCM will continuously write the certificate to the cert store. This isn't a problem if the config is only applied once, but if the LCM is set to continuously apply the config then there could be unwanted side affects.

That said, it might still be a possible solution. @johlju - any thoughts on this?

**Comment by mattbowes** [comment]
@PlagueHO that makes sense. What about adding a seperate option like  `EnsureFileSystemPrivateKey = True`

Which then performs the check `$certificate.PrivateKey.CspKeyContainerInfo`? Would that be able to solve the failed test case?

**Comment by johlju** [comment]
I agree with @PlagueHO on this one, having a `-Force` that removes and adds the certificate every 15 minutes could potentially lead to problems when the certificate the seconds the certificate is missing. Also it could potentially lead to that an application that is dependent on the certificate don't see it being added back.

What if `certutil –repairstore my <serial number>` (the actual command might need to change) is ran on the certificate, would that change the `$certificate.HasPrivateKey` to `$false`? Would it be safe to run this on a correct certificate? Though, it feels wrong running this in the `Test-TargetResource` or `Get-TargetResource`.  But having that on a `-Force` parameter would feel better when the certificate is not removed. But only if "repair" cannot make other problems.

**Comment by johlju** [comment]
@mattbowes According to @PlagueHO https://github.com/PowerShell/CertificateDsc/pull/134#issuecomment-391845638 the property `CspKeyContainerInfo` generates false negatives.

**Comment by PlagueHO** [comment]
I haven't managed to find time to progress on investigation on this one.

**Comment by PlagueHO** [comment]
Update: I have tried to find a good way to detect if the private key is present, but so far haven't been able to.

**Comment by gaelcolas** [comment]
Hi there,
How sure are you that the Private key is not there?
I've seen instances where the **object** `X509Certificate2` returns `$null` for the `PrivateKey` property, while `hasPrivateKey` is `$true`, and the certificate actually there...
Just making sure we're not barking at the wrong tree, it might be the issue with the Certificate Provider or the .Net class used underneath.

See this: https://www.ssl.com/how-to/fix-the-iis-7-no-private-key-error-message/

**Comment by PlagueHO** [comment]
Hi @gaelcolas - it is possible we've been barking up the wrong tree (been a while since I worked on this one). But it was definitely one of the head scratches that could benefit from a fresh pair of eyes! It is a more difficult one to solve because it only occurs for machines that have been Syspreped.

**Comment by johlju** [comment]
I have needed to repair the store after we “lost” a lot of certificates on a couple of servers. If the solution to this is to connect the certificate with its private key again (the repair), then maybe either this resource should support a “TryRepair” parameter when this scenario is detected, or just an entire new resource that supports repair. :thinking:

**Comment by PlagueHO** [comment]
It does appear that the Private Key does become unlinked from the certificate in the store. Is there as specific process you're aware of to repair this that we could use @johlju ?

**Comment by gaelcolas** [comment]
If it's still in the request field, the certutil command Johan provided
should work. That's the most likely issue IMO.

**Comment by PlagueHO** [comment]
Thanks @gaelcolas - I completely missed the command @johlju posted!!!! Wow! I'll have to give this a try as it is easy to reproduce - it would be good to solve this one.

**Comment by gaelcolas** [comment]
After more reading and testing, I found that most likely the Private key might have actually been removed (or is inaccessible) after sysprep, here's why:
Simplified from this excellent post: http://paulstovell.com/blog/x509certificate2
The Public key is (usually) written to registry, and the Private key written to file (never stored together, unless exported to PFX), either with system/machine files or User data. The point is that it's only 'linked' by the .Net object, but not really the same thing at all, and stored differently.

When the cert request is still stored with all info, a `/repairstore` can fix that issue.
But sysprep destroys personal data to generalise the machine, hence probably why I think it's lost.
Even if the file is still there, it can be inaccessible, because of permissions.

Anyhow, up until .Net 4.8 (with [`GetRSAPrivateKey()`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.rsacertificateextensions.getrsaprivatekey?view=netframework-4.8&viewFallbackFrom=netframework-4.0)) there's no easy way to get the Private key, and **I'm yet to find a nice way to find if the Private key is actually available** on the system or not (something quick we can run every 15min).
Until then, there's not much we can do on the resource side.

I'd vote to close the PR, update the doc and leave the issue open. What do you think @johlju 	& @PlagueHO?

**Comment by PlagueHO** [comment]
Hi @gaelcolas -great research. That also matches what I was seeing - the cert still appears in the store but the private key file is missing from the disk.

So I agree - we should close the PR and update the issue. We should also add documentation of the problem and list it as a known issue with the following solution: Don't sysprep golden images including private keys.

**Comment by gaelcolas** [comment]
Ok, updated the issue. Closing this PR.
We'd need to document (or find a fix/workaround) this before we can close the issue.

**Pull request closed without merging**
