### PR TITLE
PfxImport - Enable Re-import if Private Key not installed - Fixes #129

### LINKED ISSUE #125: xPfxImport: Parameter Description
**Details of the scenario you tried and the problem that is occurring:**
Hi, mainly looking to clarify the descriptions inside this DSC configuration.. I'm sure the code is fine.

"Path" - _The Windows Certificate Store Location to import the PFX file to._
"Location" - _The Windows Certificate Store Location to import the PFX file to._
"Store - _The Windows Certificate Store Name to import the PFX file to._

My understanding is that "Path" should actually point to the path of the .PFX file you are trying to import.. but maybe I'm missing something.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Master

Thanks!
Bennett

### LINKED ISSUE #127: Test-Thumbprint Displays Not Valid Hash Message when Hash is Valid
**Details of the scenario you tried and the problem that is occurring:**
`Test-Thumbprint` displays a verbose message stating hash is invalid when it is valid and vice versa. It also does not display hash algorithm that fails.

image

I'll submit a PR.

**The DSC configuration that is using the resource (as detailed as possible):**
All

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
All, dev

### LINKED ISSUE #129: xPfxImport does not import after sysprep
**Details of the scenario you tried and the problem that is occurring:**

After syspreping a server, the certificate is left in the cert store but the private key is removed during the sysprep process. xPfxImport only checks to ensure the thumbprint is present. It does not check to see if the certificate has a private key so it never imports the pfx file and the certificate. 

**The DSC configuration that is using the resource (as detailed as possible):**

xPfxImport Wildcard
        {
            Thumbprint = $wildcardthumbprint
            Path       = $certificatepath
            Location   = 'LocalMachine'
            Store      = 'My'
            Exportable = $true
            Credential = $Credential1
            Ensure     = 'Present'
            DependsOn  = "[xDSCDomainjoin]JoinDomain"
        }

**Version of the Operating System and PowerShell the DSC Target Node is running:**

DSC running in Azure
OS version: 2012R2

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

xCertificate 3.2.0.0

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR changes PfxImport so that it will reimport PFX if private key is not installed.

It also refactors some code in PfxImport and moves it into CertificateDsc.Common. It also improves the unit and integration tests to meet standards and improve coverage.

Full details:

- PfxImport:
  - Changed so that PFX will be reimported if private key is not
    installed - fixes [Issue #129](https://github.com/PowerShell/CertificateDsc/issues/129).
  - Corrected to meet style guidelines.
  - Corrected path parameter description - fixes [Issue #125](https://github.com/PowerShell/CertificateDsc/issues/125).
  - Refactored to remove code duplication by creating Get-CertificateStorePath.
  - Improved unit tests to meet standards and provide better coverage.
  - Improved integration tests to meet standards and provide better coverage.
- CertificateDsc.Common:
  - Corrected to meet style guidelines.
  - Added function Get-CertificateStorePath for generating Certificate Store path.
  - Remove false verbose message from `Test-Thumbprint` - fixes [Issue #127](https://github.com/PowerShell/CertificateDsc/issues/127).

**This Pull Request (PR) fixes the following issues:**
- Fixes #129 
- Fixes #127 
- Fixes #125

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - would you mind reviewing this one if you get a chance?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/130)

### CODE REVIEW

**Comment by johlju** [comment]
Just minor comments.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQI1oO1vnRckPhving:-LBQI1oO1vnRckPhvinh:b-3vc8g8) (no related file):*
The tests are failing, probably a simple problem. :slightly_smiling_face: 

---

*[Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 765 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQAtyg-AnrchotEYzl:-LBQAtyh5vbNreC7b3MV:b-i1cguq) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L765)):*
> ```PowerShell
>     [CmdletBinding()]
>     [OutputType([System.String])]
>     param (
> ```

parenthesis on the next row

---

*[Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1, line 107 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQBYusCFvPaXONFiiv:-LBQBYusCFvPaXONFiiw:b96ash3) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1#L107)):*
> ```
> needs to be
> ```

maybe "need to have a private key"?

---

*[Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1, line 150 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQBxViDDriYOfybUEE:-LBQBxViDDriYOfybUEF:b-snhgiv) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1#L150)):*
> ```PowerShell
>                 $certificateNew = Get-Item `
>                     -Path "Cert:\LocalMachine\My\$($certificate.Thumbprint)"
>                 $certificateNew                             | Should -BeOfType System.Security.Cryptography.X509Certificates.X509Certificate2
> ```

Just to make sure. Does this `Should` ensure that the certificate has a private key? If it didn't this would be of another type? 

---

*[Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1, line 156 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQBO3p61Y1CYqATukN:-LBQBO3p61Y1CYqATukO:bu9lt9q) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1#L156)):*
> ```
> 'When certificate has already been imported and needs to be'
> ```

Phrasing seems wrong, depending on how you read it. Needs to be what? :)

---

*[Tests/Unit/MSFT_PfxImport.Tests.ps1, line 82 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQGfjt8i2ayxiK8gAX:-LBQGfjt8i2ayxiK8gAY:b1h3agq) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Unit/MSFT_PfxImport.Tests.ps1#L82)):*
> ```
> yhe
> ```

the

---

*[Tests/Unit/MSFT_PfxImport.Tests.ps1, line 104 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQHFRs2wj-nggRqxKQ:-LBQHFRs2wj-nggRqxKR:b-qeu7k5) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Unit/MSFT_PfxImport.Tests.ps1#L104)):*
> ```
> exected
> ```

expected

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/130#-:-LBQI8fu6PdFgnJQ77Nw:blf4w0)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQI1oO1vnRckPhving:-LBUr9tSADn80I4DaVFj:b-lukmla) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The tests are failing, probably a simple problem. :slightly_smiling_face: 
</blockquote></details>

I'm not actually sure why the tests are failing. They pass on my machine and the integration tests for the resource that is failing wasn't changed. I'll see what happens after my next commit.

---

*[Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 765 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQAtyg-AnrchotEYzl:-LBUnPTUE9TUOFswLg5K:b-896fix) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L765)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

parenthesis on the next row
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1, line 107 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQBYusCFvPaXONFiiv:-LBUoEZI6n2e6ys_rHJp:b-896fix) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1#L107)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> needs to be
> ```

maybe "need to have a private key"?
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1, line 150 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQBxViDDriYOfybUEE:-LBUoaS_6TV0RTaSEePZ:b2ti2b) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1#L150)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Just to make sure. Does this `Should` ensure that the certificate has a private key? If it didn't this would be of another type? 
</blockquote></details>

If the PrivateKey was missing then the Ensure would be 'Absent' - so I've added a test for Ensure = 'Present'

---

*[Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1, line 156 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQBO3p61Y1CYqATukN:-LBUqpo89A6ojqgDiN0I:b9dwda5) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1#L156)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 'When certificate has already been imported and needs to be'
> ```

Phrasing seems wrong, depending on how you read it. Needs to be what? :)
</blockquote></details>

I've actually reworded the context as I really don't think the "and needs to be" was really useful anyway.

---

*[Tests/Unit/MSFT_PfxImport.Tests.ps1, line 82 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQGfjt8i2ayxiK8gAX:-LBUr29h1X0sXmhfZFMU:b-896fix) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Unit/MSFT_PfxImport.Tests.ps1#L82)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> yhe
> ```

the
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_PfxImport.Tests.ps1, line 104 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQHFRs2wj-nggRqxKQ:-LBUr6dED0R9pi5GlMyw:b-896fix) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Unit/MSFT_PfxImport.Tests.ps1#L104)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> exected
> ```

expected
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/130)*

**Comment by PlagueHO** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQI1oO1vnRckPhving:-LBV2KUP7T6NfYoonJw4:b-d41ptj) (no related file):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I'm not actually sure why the tests are failing. They pass on my machine and the integration tests for the resource that is failing wasn't changed. I'll see what happens after my next commit.
</blockquote></details>

Should be good to go now @Johlju

---

*[Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1, line 150 at r1](https://reviewable.io/reviews/powershell/certificatedsc/130#-LBQBxViDDriYOfybUEE:-LBV2Dnw-b_7GDEK1qZK:b39ypen) ([raw file](https://github.com/powershell/certificatedsc/blob/ead1d65d9cea7d8cfc063f6470b4ebe83afb6645/Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1#L150)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If the PrivateKey was missing then the Ensure would be 'Absent' - so I've added a test for Ensure = 'Present'
</blockquote></details>

I changed this to check for the HasPrivateKey instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/130)*

**Comment by johlju** [comment]
:lgtm:

Awesome work as usually! :smiley: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/130#-:-LBVEmVwAMBCuo5JTwPF:bqp7tjk)*

**Comment by johlju** [comment]
Tested the built in review process against Reviewable, but seem that comes in the next iteration of the "new" Reviewable.  🙂

**Pull request merged**
