### PR TITLE
CertReq: Removed hardcoded references

### LINKED ISSUE #207: CertReq: Multiple certificates issued when having 3rd party CA
#### Details of the scenario you tried and the problem that is occurring
When using a third party CA, such as a HSM, and issuing a certificate with CertReq, each time the LCM runs the configuration it will issue a new certificate.
This behavior is due to a hardcoded element in the function Compare-CertificateIssuer and the fact that not all CA formats the issuer with CN in the beginning.

MS CA issuer: CN=LabCA, DC=Lab, DC=local
HSM CA issuer: DC=Lab, DC=local, CN=LabCA

#### Verbose logs showing the problem
n/a (In my lab I don't have a HSM as CA, and when using MS CA this issue never occur. Also, since the certificate keep getting issued, no error message is received.)

#### Suggested solution to the issue
Remove the hard coded element in the function so that the first value of the array isn't always used, but the value that contains "CN=" no matter in which order it is placed.
I have tested code to fix this and will submit a PR after creating this bug report.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
The DSC config isn't really relevant here, but below is the issue in the code:
```powershell
return ($Issuer.split(',')[0] -eq "CN=$CARootName")
```
Forcing it to go for the first object in the split array causes it to find no match (since CN= is placed in the end, not the beginning), thus making $Certificate empty and Test-TargetResource returns $false, making DSC believe that a new cert should be issued.

#### The operating system the target node is running
Windows Server 2016

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
4.7.0.0 master

### PR DESCRIPTION
**Pull request by p0shkar**
#### Pull Request (PR) description
Removed hardcoded reference in Compare-CertificateIssuer and Get-TargetResource.
This should fix an issue with third party CA's/HSM's which does not necessarily format the CN in the same order as a Microsoft CA does. This issue caused the CA to issue a new cert each time DSC was run even though a valid certificate existed.

#### This Pull Request (PR) fixes the following issues
- Fixes #207 

#### Task list
- [x] Added an entry under the Unreleased section of the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/209)

### CODE REVIEW

**Comment by p0shkar** [comment]
> P.S. If you're signed up for #hacktoberfest and this PR will count towards it 😁

@PlagueHO I wasn't, since it's my first ever PR, but am now :) 

I will adjust the code as you suggest within a few days, good catch.

**Comment by p0shkar** [comment]
So... 2 hours later instead of a few days, apparently I couldn't keep away...

What would be a good name for the parameter of this function? I'm leaning towards "DistinguishedName" since it's the X500 DN which will be the input, but I'm open for suggestions.

Also, I could either have this new function strip the "CN=" from the result/return or keep it.
Compare-CertificateIssuer compares the the $Issuer with "CN=$CARootName".
```powershell
return (($Issuer.split(',') | ForEach-Object {$_.TrimStart(' ')} | Where-Object {$_ -match 'CN='}) -eq "CN=$CARootName")
```
I don't really see any point in keeping it this way, but instead changing it to below:
```powershell
return (($Issuer.split(',') | ForEach-Object {$_.TrimStart(' ')} | Where-Object {$_ -match 'CN='}) -eq $CARootName)
```
(Except the code above will be replaced by the function instead).

Please give me your thoughts on this.

**Comment by PlagueHO** [comment]
Hi @p0shkar - awesome timing for contributing! :grin: 

`$DistinguishedName` sounds like a good parameter name to me. As long as the tests pass and everything still works :grin: I recall looking at this a couple of years back but found there was a couple of gotchas: I think there was a couple of places where the CN= used/compared so it'll be worth confirming that. 

I'm Ok with refactoring and simplifying the code to

**Comment by p0shkar** [comment]
@PlagueHO I've pushed the refactored code for review. 

However, when looking at uses of "CN=" in the code which remains, I noticed that below code is used in Test- and Set-TargetResource, but not in Get-TargetResource.
```powershell
# If the Subject does not contain a full X500 path, construct just the CN
    if (($Subject.split('=').count) -eq 1)
    {
        $Subject = "CN=$Subject"
    }
```
And in Get-TargetResource the following code is used:
```powershell
$cert = Get-Childitem -Path Cert:\LocalMachine\My |
        Where-Object -FilterScript {
            $_.Subject -eq "CN=$Subject" -and `
            (Compare-CertificateIssuer -Issuer $_.Issuer -CARootName $CARootName)
    }
```
So if the subject contains the full X500 path, in Get-TargetResource this will result in it trying to find a Certificate with Subject "CN=CN=SomeSubject,O=Or,C=Other,S=etc". I guess it should have the same check as Test- and Set- and replace "CN=$Subject" with just "$Subject".

Could you confirm that I'm reading the code correct, that this is a bug?

**Comment by PlagueHO** [comment]
Hi @p0shkar - that does indeed look like a bug. Ideally the same code should be used for detecting the Subject should be used. If we refactor then this should be fixed.

**Comment by p0shkar** [comment]
@PlagueHO the code has been updated, I also created #210 for tracking of the bug we discussed a few weeks ago.

**Comment by p0shkar** [comment]
> Amazing job @p0shkar - loving this. Are you able to add some unit tests to cover the new `Get-CertificateCommonName` function?

Thanks @PlagueHO !

I've only dabbled a little with Pester before, and that was a while ago. Any pointers for writing unit tests and what it should test would be appreciated and helpful. :)


> ```powershell
>     return ((Get-CertificateCommonName -DistinguishedName $Issuer) -eq "$CARootName")
> ```
> 
> You can remove the quotes around the $CARootName here.

Sure, I think I left them there since I pretty much copied Compare-CertificateIssuer and wanted to make as little code-impact as possible, but I see now that it's not the same since Compare-CertificateIssuer also has "CN=" before the variable name.

> ```powershell
>     return ($DistinguishedName.split(',') | ForEach-Object {$_.TrimStart(' ')} | Where-Object {$_ -match 'CN='}).replace('CN=', '')
> ```
> 
> Could you break this line up a bit to shorten it? Also, can you use named parameters? e.g.
> 
> ```powershell
> return ($DistinguishedName.split(',') |
>     ForEach-Object -Process { $_.TrimStart(' ') } |
>     Where-Object -FilterScript { $_ -match 'CN=' }).replace('CN=', '')
> ```

Of course! Will fix that right away.

**Comment by p0shkar** [comment]
_An unrelated question: does the [DSC Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) translate into any of the [predefined styles available in VSCode](https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/81) or can a custom set be found somewhere which do the correct formatting? It would be awesome to be able to use the auto formatter when writing/updating DSC modules!_

**Comment by PlagueHO** [comment]
@p0shkar - definitely. This is something we'd like to do, but we needed to start by getting all the custom PSSA validation rules in place (so that VSCode can highlight style violations). Everything is located over here: https://github.com/PowerShell/DscResource.Tests and you can see the issues/PRs tracking that over there.

**Comment by p0shkar** [comment]
@PlagueHO I've added a couple of tests, I couldn't think of any more which would be appropriate so I hope this is enough or you could give me some pointers.

**Comment by p0shkar** [comment]
@PlagueHO Of course, good idea! The whole idea of this PR is for that to work, so can't believe I didn't think of that.. The changes has been pushed.

Don't know if you noticed in [commit 6ba9bd3](https://github.com/PowerShell/CertificateDsc/pull/209/commits/6ba9bd3e3a56d5376fb8edf69a73210d53629a82), but when looking at the other tests I found that the "It"-name said "should return true" while the "should"-statement returned $false, so I fixed that even though it doesn't really have anything to do with this PR.

**Pull request merged**
