### PR TITLE
Test-CertificateAuthority: Fixed issue where the DisplayName is returned instead of the Name of the template

### LINKED ISSUE #147: Get-CertificateTemplateName returns certificate displayname instead of name when Oid is 1.3.6.1.4.1.311.21.7  Certificate Template Information
I'm having problems with CertReq when specifying the template name. If I use the name of the template then the certificate request gets the certificate but the test fails to match the certificate to the supplied template name the second time DSC runs.
If I supply the template display name the certificate request is rejected.

I believe the problem occurs when then the certificate that is requested uses the Oid 1.3.6.1.4.1.311.21.7  Certificate Template Information. The data returns the template display name.

### PR DESCRIPTION
**Pull request by rcarpenter79**
When the certificate uses OID 1.3.6.1.4.1.311.21.7 the template is referred to by the display name.
This is then returned and compared to the template name from the resource, which won't match.
A new certificate is then requested.

This change looks up the display name of the template and returns the name of the template instead.
If no match is found it returns the name that was found in the OID so the behaviour stays the same after this change in this case.

Fixes #147 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/148)

### CODE REVIEW

**Comment by johlju** [comment]
@rcarpenter79 I think @PlagueHO will be back shortly to continue the review.

**Comment by rcarpenter79** [comment]
@PlagueHO  Is there anything else that I need to do?

**Comment by PlagueHO** [comment]
Doh! Sorry @rcarpenter79 - ball is in my court! I dropped it. I'll get it done tomorrow night after work. Thank you for prompting me!

**Comment by rcarpenter79** [comment]
@PlagueHO I think all the points you raised have been addresses.
If you could review when you have a chance, that would be great.

**Pull request merged**
