### PR TITLE
Moved Code of Conduct to separate file - Fixes #139

### LINKED ISSUE #139: Add Code of Conduct
See https://github.com/PowerShell/DscResources/issues/337#issuecomment-395776698

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Moved Code of Conduct to separate file.

**This Pull Request (PR) fixes the following issues:**
- Fixes #139

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@Johlju - would you mind reviewing? Should be just standard Code of Conduct change.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/140)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@johlju - doh! Yes I did. Forgot I had another outstanding branch on this repo! Will fix it tonight.

**Comment by PlagueHO** [comment]
Actually, I'll fix up this one once #137 has been reviewed and merged.

**Comment by PlagueHO** [comment]
This one should be good to go now @johlju - sorry about the mess up!

**Comment by johlju** [comment]
:lgtm:

No worries - it happens :smiley: 

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/140#-:-LFO_PjpCNoJbcaDmAd7:bfl5l3j)*

**Pull request merged**
