### PR TITLE
CertificateDSC: Adding ECDH key lengths and Request Type PKCS10

### LINKED ISSUE #113: xCertReq: Permit ECDH key-lengths
**Details of the scenario you tried and the problem that is occurring:**
When attempting to use xCertReq to request an ECDH certificate, you typically use a key length of 192, 224, 256, 384 or 521. Currently if you try to specify one of those key lengths, the module throws an error of:
```
At least one of the values '256' is not supported or valid for property 'KeyLength' on class 'xCertReq'. Please
specify only supported values:
1024, 2048, 4096, 8192.
```
Patching this in for a one-off is simple enough, but it is a "dumb" patch that permits any of the key sizes for any of the certificates, even if they are not valid for that certificate type. Maybe that's a valid workaround for this module? If so, more than happy to provide a PR.

E.g. RSA keys should have `1024, 2048, 4096, 8192`, but EDCH keys should have `192, 224, 256, 384, 521`

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016, PSVersion 5.1.14393.1884

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
3.0.0.0

### PR DESCRIPTION
**Pull request by rchristman89**
#### Pull Request (PR) description
Added parameter to choose if ECDH or RSA key types are being used in an effort to ensure the right key length is chosen. Added additional key lengths to support ECDH. 

Added parameter to change the request type to PKCS10 if needed. 

#### This Pull Request (PR) fixes the following issues
    - Fixes #113 

#### Task list

- [X] Added an entry under the Unreleased section of the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/certificatedsc/175)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @rchristman89 - it looks like the examples are failing to compile https://ci.appveyor.com/project/PowerShell/certificatedsc/builds/21506279?fullLog=true#L528 and also the changelog.md has an issue: https://ci.appveyor.com/project/PowerShell/certificatedsc/builds/21506279?fullLog=true#L580

**Comment by rchristman89** [comment]
@PlagueHO if you have any ideas on the two failure now I would be interested. 
"Expected no exception to be thrown, but an exception "Cannot process command because of one or more missing mandatory parameters: Credential." was thrown from C:\projects\certificatedsc\DscResource.Tests\Meta.Tests.ps1:643 char:29"

**Comment by rchristman89** [comment]
@PlagueHO I will take a look at the integration tests. I was having issues getting them to work in my lab before I made any changes so I moved on without updating them. I will get back to you on them.

**Comment by PlagueHO** [comment]
Awesome @rchristman89 . I'm just travelling at the moment but will try and get the review complete when I'm at a computer (on phone atm). Thanks again!

**Comment by rchristman89** [comment]
@PlagueHO Wanted to check in. Does anything else need addressed?

**Comment by PlagueHO** [comment]
Sorry for taking so long! Still away from computer, travelling for work. Will definitely complete review asap,but not back till Tuesday. Using phone for review not so great! :cry:

**Comment by PlagueHO** [comment]
Hi @rchristman89 - are you able to rebase to resolve the conflicts and then we'll aim to knock this one one.

**Comment by rchristman89** [comment]
@PlagueHO  I think I covered all you suggested. Let me know if there is anything else. Thanks for follow up.

**Comment by PlagueHO** [comment]
Hi @rchristman89 - it looks like there are some merge conflicts caused by another PR that got merged. Can you resolve these and I'll finish up the review? Thank you again!

**Comment by PlagueHO** [comment]
Hi @rchristman89 - it looks like you're missing a CRLF at the end of MSFT_CertReq.psm1 file: https://ci.appveyor.com/project/PowerShell/certificatedsc/builds/21846213?fullLog=true#L178

There are also some other test failures: https://ci.appveyor.com/project/PowerShell/certificatedsc/builds/21846213?fullLog=true#L1494

**Comment by rchristman89** [comment]
@PlagueHO I believe I have resolved all conflicts and made all previous changes.

**Comment by PlagueHO** [comment]
Cool. Thanks @rchristman89 - I'll try and get reviewed tomorrow night.

**Comment by rchristman89** [comment]
@PlagueHO  i believe i fixed everything. I apologize I believe when going through the Merge Conflicts I made some mistakes.

**Comment by PlagueHO** [comment]
No worries @rchristman89 - you should see the number of mistakes I make :grin: There are still a couple of tests failing: https://ci.appveyor.com/project/PowerShell/certificatedsc/builds/22059402?fullLog=true#L1703

Let me know if you need a hand figuring out the issue. It would be awesome to get this one in!

**Comment by rchristman89** [comment]
@PlagueHO alright fixed my failed tests. Let me know if you see anything else.

**Pull request merged**
